server:
  port: 8080


spring:
  application:
    name: Car
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/CarDB?autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul"
    username: root
    password: 7328
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  logging.level:
    org.hibernate.SQL: debug
